import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import type {
  AccountExportInput,
  AccountExportResult,
  AccountImportProgress,
  AccountTransferProgress,
  CandidateRuntimeSnapshot,
  ConfirmAccountImportResponse,
  ConfigurationPresetApplyResult,
  ConfigurationPresetPreview,
  ConsumeResetCreditResponse,
  DefaultServiceTier,
  ImportSession,
  LocalUsagePage,
  OpenCodeConfigStatus,
  MoveAccountsToRemoteResult,
  OAuthFlow,
  OAuthFlowEvent,
  OAuthCompletion,
  ProfileActivation,
  ProfileBinding,
  ProfileSnapshot,
  ProfileSnapshotList,
  ProxyPoolImportResult,
  ProxyPoolSummary,
  RelayStorageInfo,
  RevealedAccountIdentity,
  RemoteTarget,
  RemoteUsagePage,
  RemoteUsageQuery,
  RoutingStrategy,
  RuntimeActivitySnapshot,
  RuntimeSnapshot,
  SourceStats,
  SupportExportContext,
  SupportBundlePreview,
  StoredProxyAssignmentResult,
  UsageExportRow,
  WakeTask,
} from "./types";

export type UiState = {
  providerActive: boolean;
  codexRunning: boolean;
  hasSavedApiKey: boolean;
};

export const relayCommands = {
  readyState: () => invoke<UiState>("get_state"),
  onStateChanged: (callback: () => void) => listen("zenith-state-changed", callback),
  onRuntimeActivity: (callback: (activity: RuntimeActivitySnapshot) => void) => listen<RuntimeActivitySnapshot>("zenith-runtime-activity", (event) => callback(event.payload)),
  onUsageRecorded: (callback: () => void) => listen("zenith-usage-recorded", callback),
  localState: () => invoke<RuntimeSnapshot>("get_local_runtime_state"),
  localRuntimeOrder: () => invoke<CandidateRuntimeSnapshot[]>("get_local_runtime_order"),
  remoteState: () => invoke<RuntimeSnapshot | null>("get_remote_server_state"),
  remoteRuntimeOrder: () => invoke<CandidateRuntimeSnapshot[] | null>("get_remote_runtime_order"),
  remoteUsage: (input: RemoteUsageQuery = {}) => invoke<RemoteUsagePage | null>("get_remote_server_usage", { input }),
  revealRemoteGatewayApiKey: () => invoke<string>("reveal_remote_gateway_api_key"),
  rotateRemoteGatewayApiKey: () => invoke<string>("rotate_remote_gateway_api_key"),
  localUsagePage: (input: RemoteUsageQuery = {}) => invoke<LocalUsagePage>("get_local_usage_page", { input }),
  clearLocalUsage: () => invoke("clear_local_usage"),

  createSource: (input: Record<string, unknown>) => invoke("create_local_source", { input }),
  updateSource: (input: Record<string, unknown>) => invoke("update_local_source", { input }),
  rotateSourceKey: (sourceId: string, apiKey: string) => invoke("rotate_local_source_key", { sourceId, apiKey }),
  setSourceEnabled: (sourceId: string, enabled: boolean) => invoke("set_local_source_enabled", { sourceId, enabled }),
  deleteSource: (sourceId: string) => invoke("delete_local_source", { sourceId }),
  testSource: (sourceId: string) => invoke("test_local_source", { sourceId }),
  refreshSourceData: (sourceId: string) => invoke("refresh_local_source_data", { sourceId }),
  localSourceStats: (sourceId: string) => invoke<SourceStats>("get_local_source_stats", { sourceId }),
  remoteSourceStats: (sourceId: string) => invoke<SourceStats>("get_remote_source_stats", { sourceId }),

  startImport: (content: string) => invoke<ImportSession>("start_local_account_import", { input: { content } }),
  previewImportFiles: (paths?: string[]) => invoke<ImportSession | null>("preview_local_account_import_files", paths ? { paths } : {}),
  previewCurrentCodexImport: () => invoke<ImportSession>("preview_current_codex_account_import"),
  currentChatgptProfileAvailable: () => invoke<boolean>("current_chatgpt_profile_available"),
  previewRemoteImportFiles: (paths?: string[]) => invoke<ImportSession | null>("preview_remote_account_import_files", paths ? { paths } : {}),
  prepareImport: (sessionId: string, probeQuota = false) => invoke<ImportSession>("prepare_local_account_import", { input: { sessionId, probeQuota } }),
  confirmImport: (sessionId: string, selectedItemIds: string[], addToPool = false) => invoke<ConfirmAccountImportResponse>("confirm_local_account_import", { input: { sessionId, selectedItemIds, discoverModels: false, probeQuota: false, models: [], addToPool } }),
  onImportProgress: (callback: (event: AccountImportProgress) => void) => listen<AccountImportProgress>("relay-account-import-progress", (event) => callback(event.payload)),
  cancelImport: (sessionId: string) => invoke("cancel_local_account_import", { sessionId }),
  refreshAccountQuota: (accountId: string) => invoke("refresh_local_account_quota", { accountId }),
  refreshAllAccountQuotas: () => invoke<Array<{ accountId: string; status: "succeeded" | "failed" }>>("refresh_all_local_account_quotas"),
  consumeResetCredit: (accountId: string) => invoke<ConsumeResetCreditResponse>("consume_local_reset_credit", { accountId }),
  updateAccount: (input: Record<string, unknown>) => invoke("update_local_account", { input }),
  setAccountEnabled: (accountId: string, enabled: boolean) => invoke("set_local_account_enabled", { accountId, enabled }),
  deleteAccount: (accountId: string) => invoke("delete_local_account", { accountId }),
  deleteAccounts: (accountIds: string[]) => invoke("delete_local_accounts", { accountIds }),
  setAccountProxy: (accountId: string, proxyUrl: string | null, bypassCommonProxy = false) => invoke("set_local_account_proxy", { input: { accountId, proxyUrl, bypassCommonProxy } }),
  getProxyPool: () => invoke<ProxyPoolSummary>("get_local_proxy_pool"),
  importProxyPool: (proxyUrls: string[]) => invoke<ProxyPoolImportResult>("import_local_proxy_pool", { input: { proxyUrls } }),
  deleteStoredProxy: (proxyId: string) => invoke<ProxyPoolSummary>("delete_local_stored_proxy", { proxyId }),
  deleteStoredProxies: (proxyIds: string[]) => invoke<ProxyPoolSummary>("delete_local_stored_proxies", { input: { proxyIds } }),
  assignStoredProxy: (accountId: string, proxyId: string) => invoke<StoredProxyAssignmentResult>("assign_local_stored_proxy", { input: { accountId, proxyId } }),
  setStoredProxyAccounts: (proxyId: string, accountIds: string[]) => invoke<StoredProxyAssignmentResult>("set_local_stored_proxy_accounts", { input: { proxyId, accountIds } }),
  assignAutomaticProxies: (accountIds: string[]) => invoke<StoredProxyAssignmentResult>("assign_free_local_account_proxies", { input: { accountIds } }),
  exportLocalAccounts: (input: AccountExportInput) => invoke<AccountExportResult>("export_local_accounts", { input }),
  exportRemoteAccounts: (input: AccountExportInput) => invoke<AccountExportResult>("export_remote_accounts", { input }),
  moveAccountsToRemote: (accountIds: string[]) => invoke<MoveAccountsToRemoteResult>("move_local_accounts_to_remote", { input: { accountIds } }),
  returnAccountToLocal: (localAccountId: string) => invoke<{ localAccountId: string }>("return_remote_account_to_local", { input: { localAccountId } }),
  forceActivateRemoteAccountLocally: (localAccountId: string) => invoke<{ localAccountId: string }>("force_activate_remote_account_locally", { input: { localAccountId, confirmRemoteMayStillBeRunning: true } }),
  onAccountTransferProgress: (callback: (event: AccountTransferProgress) => void) => listen<AccountTransferProgress>("relay-account-transfer-progress", (event) => callback(event.payload)),
  revealLocalAccountIdentity: (accountId: string) => invoke<RevealedAccountIdentity>("reveal_local_account_identity", { accountId }),
  revealRemoteAccountIdentity: (accountId: string) => invoke<RevealedAccountIdentity>("reveal_remote_account_identity", { accountId }),

  startOAuth: (openBrowser = true, accountId?: string) => invoke<OAuthFlow>("start_codex_oauth", { openBrowser, ...(accountId ? { accountId } : {}) }),
  resumeOAuth: (loginId: string) => invoke<OAuthFlow>("resume_codex_oauth", { loginId }),
  onOAuthStatus: (callback: (event: OAuthFlowEvent) => void) => listen<OAuthFlowEvent>("relay-oauth-status", (event) => callback(event.payload)),
  completeOAuth: (loginId: string) => invoke<OAuthCompletion>("complete_codex_oauth", { loginId }),
  cancelOAuth: (loginId: string) => invoke("cancel_codex_oauth", { loginId }),

  setPoolMembership: (accountIds: string[], sourceIds: string[], inPool: boolean) => invoke("set_local_pool_membership", { input: { accountIds, sourceIds, inPool } }),
  setModelEnabled: (modelId: string, enabled: boolean) => invoke("set_local_model_enabled", { input: { modelId, enabled } }),
  setModelPrice: (modelId: string, inputMicroUsdPerMillion: number | null, cachedInputMicroUsdPerMillion: number | null, cacheWrite5mMicroUsdPerMillion: number | null, cacheWrite1hMicroUsdPerMillion: number | null, outputMicroUsdPerMillion: number | null) => invoke("set_local_model_price", { input: { modelId, inputMicroUsdPerMillion, cachedInputMicroUsdPerMillion, cacheWrite5mMicroUsdPerMillion, cacheWrite1hMicroUsdPerMillion, outputMicroUsdPerMillion } }),
  setModelReasoning: (modelId: string, allowedLevels: string[]) => invoke("set_local_model_reasoning", { input: { modelId, allowedLevels } }),
  setModelServiceTier: (modelId: string, serviceTier: DefaultServiceTier) => invoke("set_local_model_service_tier", { input: { modelId, serviceTier } }),
  setModelDisplayOrder: (modelIds: string[]) => invoke("set_local_model_display_order", { input: { modelIds } }),
  exportLocalConfigurationPreset: () => invoke<string | null>("export_local_configuration_preset"),
  previewLocalConfigurationPreset: () => invoke<ConfigurationPresetPreview | null>("preview_local_configuration_preset"),
  applyLocalConfigurationPreset: (preview: ConfigurationPresetPreview) => invoke<ConfigurationPresetApplyResult>("apply_local_configuration_preset", { input: { baseRevision: preview.baseRevision, preset: preview.preset } }),
  updateRouting: (routingStrategy: RoutingStrategy, maxRetryCandidates: number, cooldownAfterFailures: number, keepLastCandidateAvailable: boolean, defaultServiceTier: DefaultServiceTier, subscriptionPlanOrder: string[]) => invoke("update_local_routing", { input: { routingStrategy, maxRetryCandidates, cooldownAfterFailures, keepLastCandidateAvailable, defaultServiceTier, subscriptionPlanOrder } }),
  syncCodexDefaultServiceTier: (defaultServiceTier: DefaultServiceTier) => invoke<void>("sync_codex_default_service_tier", { defaultServiceTier }),
  startGateway: () => invoke("start_local_gateway"),
  stopGateway: () => invoke("stop_local_gateway"),
  restartGateway: () => invoke("restart_local_gateway"),
  updateGatewayPort: (port: number) => invoke("update_local_gateway_port", { port }),
  revealLocalGatewayApiKey: () => invoke<string>("reveal_local_gateway_api_key"),
  rotateLocalGatewayApiKey: () => invoke<string>("rotate_local_gateway_api_key"),
  updateChatgptQuotaReserve: (reserveBasisPoints: number) => invoke("update_chatgpt_interface_quota_reserve", { input: { reserveBasisPoints } }),
  setCommonProxy: (proxyUrl: string | null) => invoke("set_local_common_proxy", { input: { proxyUrl } }),
  setAccountProxyRequired: (required: boolean) => invoke("set_local_account_proxy_required", { input: { required } }),
  setCodexBackgroundTasks: (enabled: boolean) => invoke("set_local_codex_background_tasks", { input: { enabled } }),
  setRemoteCodexBackgroundTasks: (enabled: boolean) => invoke("execute_remote_server_action", { input: { action: { type: "set_codex_background_tasks" }, payload: { enabled } } }),
  setCodexWebsockets: (enabled: boolean) => invoke("set_local_codex_websockets", { input: { enabled } }),
  setCodexProfileWebsockets: (enabled: boolean) => invoke("set_codex_profile_websockets", { input: { enabled } }),
  setRemoteCodexWebsockets: (enabled: boolean) => invoke("execute_remote_server_action", { input: { action: { type: "set_codex_websockets" }, payload: { enabled } } }),

  createAutomation: (input: Record<string, unknown>) => invoke("create_quota_wake_automation", { input }),
  updateAutomation: (taskId: string, input: Record<string, unknown>) => invoke("update_quota_wake_automation", { taskId, input }),
  setAutomationEnabled: (taskId: string, enabled: boolean) => invoke("set_quota_wake_automation_enabled", { taskId, enabled }),
  deleteAutomation: (taskId: string) => invoke("delete_quota_wake_automation", { taskId }),
  runWakeConfirmations: () => invoke<number>("run_due_quota_wake_confirmations", { maxClaims: 2 }),
  testAutomation: (taskId: string) => invoke<{ taskId: string; status: string; eligibleAccounts: number }>("test_quota_wake_automation", { taskId }),

  attachCodexGateway: (boundOauthAccountId: string | null = null, disableOauthBinding = false) => invoke<ProfileActivation>("attach_codex_to_local_gateway", { boundOauthAccountId, ...(disableOauthBinding ? { disableOauthBinding: true } : {}) }),
  attachCodexRemoteGateway: () => invoke<ProfileActivation>("attach_codex_to_remote_gateway"),
  stopManagedCodex: () => invoke<boolean>("stop_managed_codex_profile"),
  launchManagedCodex: () => invoke("launch_managed_codex_profile"),
  getOpenCodeConfigStatus: () => invoke<OpenCodeConfigStatus>("get_opencode_config_status"),
  connectOpenCode: () => invoke<{ path: string; modelCount: number; backupCreated: boolean }>("connect_opencode_to_local_gateway"),
  restartOpenCode: () => invoke<void>("restart_opencode_app"),
  restoreOpenCodeConfig: () => invoke<boolean>("restore_opencode_config"),
  restoreCodex: () => invoke("restore_codex_profile"),
  attachCodexAccount: (accountId: string, profileDir?: string) => invoke<ProfileActivation>("attach_codex_to_account", { accountId, profileDir: profileDir || null }),
  launchCodexAccount: (accountId: string) => invoke<ProfileActivation>("launch_codex_account", { accountId }),
  launchCodexSource: (sourceId: string) => invoke<ProfileActivation>("launch_codex_source", { sourceId }),
  profileBindings: () => invoke<ProfileBinding[]>("list_codex_account_bindings"),
  restoreAccountProfile: (profileDir: string) => invoke("restore_codex_account_profile", { profileDir }),
  restoreDefaultAccountProfile: () => invoke("restore_codex_account_profile", { profileDir: null }),
  profileSnapshots: () => invoke<ProfileSnapshotList>("list_codex_profile_snapshots"),
  createProfileSnapshot: (name: string) => invoke<ProfileSnapshot>("create_codex_profile_snapshot", { name }),
  restoreProfileSnapshot: (snapshotId: string) => invoke<void>("restore_full_codex_profile_snapshot", { snapshotId }),
  deleteProfileSnapshot: (snapshotId: string) => invoke("delete_codex_profile_snapshot", { snapshotId }),
  storageInfo: () => invoke<RelayStorageInfo>("get_relay_storage_info"),
  openFolder: (folder: "data" | "profile_backups") => invoke("open_relay_folder", { folder }),
  resetLocalData: () => invoke("reset_local_pool_data"),
  exportUsage: (rows: UsageExportRow[]) => invoke<string | null>("export_usage", { rows }),
  exportSupportBundle: (context: SupportExportContext) => invoke<string | null>("export_support_bundle", { context }),
  previewSupportBundle: (context: SupportExportContext) => invoke<SupportBundlePreview>("preview_support_bundle", { context }),

  connectRemote: (input: Record<string, unknown>) => invoke<{ target: RemoteTarget }>("connect_remote_server", { input }),
  remoteLinkedAccountCount: () => invoke<number>("get_remote_linked_account_count"),
  disconnectRemote: () => invoke("disconnect_remote_server"),
  refreshRemoteCapabilities: () => invoke("refresh_remote_server_capabilities"),
  exportRemoteConfigurationPreset: () => invoke<string | null>("export_remote_configuration_preset"),
  previewRemoteConfigurationPreset: () => invoke<ConfigurationPresetPreview | null>("preview_remote_configuration_preset"),
  applyRemoteConfigurationPreset: (preview: ConfigurationPresetPreview) => invoke<ConfigurationPresetApplyResult>("apply_remote_configuration_preset", { input: { baseRevision: preview.baseRevision, preset: preview.preset } }),
  prepareRemoteDeployment: (publicBaseUrl: string) => invoke<{ directory: string; publicBaseUrl: string; managementToken: string; vaultKey: string; composeCommand: string }>("prepare_remote_server_deployment", { input: { publicBaseUrl } }),
  remoteAction: (action: Record<string, unknown>, payload?: unknown) => invoke("execute_remote_server_action", { input: { action, payload: payload ?? null } }),
};

export function defaultWakeInput(name: string): Omit<WakeTask, "id" | "createdAtMs" | "updatedAtMs" | "trigger"> {
  return {
    name,
    enabled: true,
    accountSelector: { kind: "all_eligible" },
    windowKinds: ["primary"],
    modelPolicy: { kind: "lightest_supported" },
    executionPolicy: "automatic",
    jitterSeconds: 0,
    maxAttemptsPerCycle: 1,
  };
}
