import { invoke } from "@tauri-apps/api/core";
import type {
  AccountExportInput,
  AccountExportResult,
  ConfirmAccountImportResponse,
  GatewayDiagnostic,
  HistoryRepairPreview,
  HistoryRepairResult,
  ImportSession,
  KeySummary,
  LocalUsage,
  OpenCodeProfileState,
  OAuthFlow,
  ProfileActivation,
  ProfileBinding,
  ProfileSnapshot,
  ProxyAssignmentResult,
  RevealedAccountIdentity,
  RemoteTarget,
  RemoteUsagePage,
  RemoteUsageQuery,
  RuntimeSnapshot,
  SupportExportContext,
  SupportBundlePreview,
  UsageExportRow,
  WakeTask,
} from "./types";

export const relayCommands = {
  localState: () => invoke<RuntimeSnapshot>("get_local_runtime_state"),
  remoteState: () => invoke<RuntimeSnapshot | null>("get_remote_server_state"),
  remoteUsage: (input: RemoteUsageQuery = {}) => invoke<RemoteUsagePage | null>("get_remote_server_usage", { input }),
  localUsage: (limit = 100) => invoke<LocalUsage[]>("get_local_usage", { limit }),
  clearLocalUsage: () => invoke("clear_local_usage"),
  diagnoseRemoteGateway: (stream: boolean) => invoke<GatewayDiagnostic>("diagnose_remote_gateway", { stream }),

  createSource: (input: Record<string, unknown>) => invoke("create_local_source", { input }),
  updateSource: (input: Record<string, unknown>) => invoke("update_local_source", { input }),
  rotateSourceKey: (sourceId: string, apiKey: string) => invoke("rotate_local_source_key", { sourceId, apiKey }),
  setSourceEnabled: (sourceId: string, enabled: boolean) => invoke("set_local_source_enabled", { sourceId, enabled }),
  deleteSource: (sourceId: string) => invoke("delete_local_source", { sourceId }),
  testSource: (sourceId: string) => invoke("test_local_source", { sourceId }),

  startImport: (content: string) => invoke<ImportSession>("start_local_account_import", { input: { content } }),
  previewImportFiles: (paths?: string[]) => invoke<ImportSession | null>("preview_local_account_import_files", paths ? { paths } : {}),
  previewRemoteImportFiles: (paths?: string[]) => invoke<ImportSession | null>("preview_remote_account_import_files", paths ? { paths } : {}),
  resumeImport: (sessionId: string) => invoke<ImportSession>("resume_local_account_import", { sessionId }),
  prepareImport: (sessionId: string, probeQuota = true) => invoke<ImportSession>("prepare_local_account_import", { input: { sessionId, probeQuota } }),
  confirmImport: (sessionId: string, selectedItemIds: string[]) => invoke<ConfirmAccountImportResponse>("confirm_local_account_import", { input: { sessionId, selectedItemIds, discoverModels: true, probeQuota: true, models: [] } }),
  cancelImport: (sessionId: string) => invoke("cancel_local_account_import", { sessionId }),
  refreshAccountQuota: (accountId: string) => invoke("refresh_local_account_quota", { accountId }),
  refreshAllAccountQuotas: () => invoke("refresh_all_local_account_quotas"),
  refreshPoolAccountQuotas: () => invoke("refresh_local_pool_account_quotas"),
  updateAccount: (input: Record<string, unknown>) => invoke("update_local_account", { input }),
  setAccountEnabled: (accountId: string, enabled: boolean) => invoke("set_local_account_enabled", { accountId, enabled }),
  setAccountDraining: (accountId: string, draining: boolean) => invoke("set_local_account_draining", { accountId, draining }),
  deleteAccount: (accountId: string) => invoke("delete_local_account", { accountId }),
  setAccountProxy: (accountId: string, proxyUrl: string | null) => invoke("set_local_account_proxy", { input: { accountId, proxyUrl } }),
  assignAccountProxies: (accountIds: string[], proxyUrls: string[]) => invoke<ProxyAssignmentResult>("assign_local_account_proxies", { input: { accountIds, proxyUrls } }),
  exportLocalAccounts: (input: AccountExportInput) => invoke<AccountExportResult>("export_local_accounts", { input }),
  exportRemoteAccounts: (input: AccountExportInput) => invoke<AccountExportResult>("export_remote_accounts", { input }),
  revealLocalAccountIdentity: (accountId: string) => invoke<RevealedAccountIdentity>("reveal_local_account_identity", { accountId }),
  revealRemoteAccountIdentity: (accountId: string) => invoke<RevealedAccountIdentity>("reveal_remote_account_identity", { accountId }),

  startOAuth: () => invoke<OAuthFlow>("start_codex_oauth"),
  resumeOAuth: (loginId: string) => invoke<OAuthFlow>("resume_codex_oauth", { loginId }),
  oauthStatus: (loginId: string) => invoke<OAuthFlow>("get_codex_oauth_status", { loginId }),
  submitOAuthCallback: (loginId: string, callbackUrl: string) => invoke("submit_codex_oauth_callback", { loginId, callbackUrl }),
  completeOAuth: (loginId: string) => invoke("complete_codex_oauth", { loginId }),
  cancelOAuth: (loginId: string) => invoke("cancel_codex_oauth", { loginId }),

  createKey: (label: string) => invoke<{ key: KeySummary; secret: string }>("create_local_gateway_key", { label }),
  updateKey: (input: Record<string, unknown>) => invoke("update_local_gateway_key", { input }),
  rotateKey: (keyId: string) => invoke<{ key: unknown; secret: string }>("rotate_local_gateway_key", { keyId }),
  setKeyEnabled: (keyId: string, enabled: boolean) => invoke("set_local_gateway_key_enabled", { keyId, enabled }),
  deleteKey: (keyId: string) => invoke("delete_local_gateway_key", { keyId }),
  setPoolMembership: (accountIds: string[], sourceIds: string[], inPool: boolean) => invoke("set_local_pool_membership", { input: { accountIds, sourceIds, inPool } }),
  setModelEnabled: (modelId: string, enabled: boolean) => invoke("set_local_model_enabled", { input: { modelId, enabled } }),
  updateQuotaPolicy: (refreshIntervalSeconds: number, requestTimeoutSeconds: number, useFreeAccounts: boolean) => invoke("update_local_quota_policy", { input: { refreshIntervalSeconds, requestTimeoutSeconds, useFreeAccounts } }),
  startGateway: () => invoke("start_local_gateway"),
  stopGateway: () => invoke("stop_local_gateway"),
  restartGateway: () => invoke("restart_local_gateway"),
  updateGatewayPort: (port: number) => invoke("update_local_gateway_port", { port }),
  setCommonProxy: (proxyUrl: string | null) => invoke("set_local_common_proxy", { input: { proxyUrl } }),
  setAccountProxyRequired: (required: boolean) => invoke("set_local_account_proxy_required", { input: { required } }),
  diagnoseGateway: (stream: boolean) => invoke<GatewayDiagnostic>("diagnose_local_gateway", { stream }),

  createAutomation: (input: Record<string, unknown>) => invoke("create_quota_wake_automation", { input }),
  updateAutomation: (taskId: string, input: Record<string, unknown>) => invoke("update_quota_wake_automation", { taskId, input }),
  setAutomationEnabled: (taskId: string, enabled: boolean) => invoke("set_quota_wake_automation_enabled", { taskId, enabled }),
  deleteAutomation: (taskId: string) => invoke("delete_quota_wake_automation", { taskId }),
  runWakeConfirmations: () => invoke<number>("run_due_quota_wake_confirmations", { maxClaims: 2 }),
  testAutomation: (taskId: string) => invoke<{ taskId: string; status: string; eligibleAccounts: number }>("test_quota_wake_automation", { taskId }),

  attachCodexGateway: (keyId: string, boundOauthAccountId: string | null = null) => invoke<ProfileActivation>("attach_codex_to_local_gateway", { keyId, boundOauthAccountId }),
  attachOpenCodeGateway: (keyId: string) => invoke("attach_opencode_to_local_gateway", { keyId }),
  stopManagedCodex: () => invoke<boolean>("stop_managed_codex_profile"),
  launchManagedCodex: () => invoke("launch_managed_codex_profile"),
  restoreCodex: () => invoke("restore_codex_profile"),
  restoreOpenCode: () => invoke("restore_opencode_profile"),
  openCodeProfileState: () => invoke<OpenCodeProfileState>("get_opencode_profile_state"),
  previewHistoryRepair: (profileDirs: string[], targetProvider: "openai" | "zenith_relay_local") => invoke<HistoryRepairPreview>("preview_codex_history_repair", { input: { profileDirs, targetProvider } }),
  applyHistoryRepair: (sessionId: string) => invoke<HistoryRepairResult>("apply_codex_history_repair", { sessionId }),
  rollbackHistoryRepair: (backupId: string) => invoke<{ backupId: string; filesRestored: number }>("rollback_codex_history_repair", { backupId }),
  attachCodexAccount: (accountId: string, profileDir?: string) => invoke<ProfileActivation>("attach_codex_to_account", { accountId, profileDir: profileDir || null }),
  launchCodexAccount: (accountId: string) => invoke<ProfileActivation>("launch_codex_account", { accountId }),
  profileBindings: () => invoke<ProfileBinding[]>("list_codex_account_bindings"),
  restoreAccountProfile: (profileDir: string) => invoke("restore_codex_account_profile", { profileDir }),
  profileSnapshots: () => invoke<ProfileSnapshot[]>("list_codex_profile_snapshots"),
  createProfileSnapshot: (name: string) => invoke<ProfileSnapshot>("create_codex_profile_snapshot", { name }),
  restoreProfileSnapshot: (snapshotId: string, safetyName: string) => invoke<ProfileSnapshot>("restore_codex_profile_snapshot", { snapshotId, safetyName }),
  deleteProfileSnapshot: (snapshotId: string) => invoke("delete_codex_profile_snapshot", { snapshotId }),
  openFolder: (folder: "data" | "profile_backups") => invoke("open_relay_folder", { folder }),
  resetLocalData: () => invoke("reset_local_pool_data"),
  exportUsage: (rows: UsageExportRow[]) => invoke<string>("export_usage", { rows }),
  exportSupportBundle: (context: SupportExportContext) => invoke<string>("export_support_bundle", { context }),
  previewSupportBundle: (context: SupportExportContext) => invoke<SupportBundlePreview>("preview_support_bundle", { context }),

  connectRemote: (input: Record<string, unknown>) => invoke<{ target: RemoteTarget }>("connect_remote_server", { input }),
  disconnectRemote: () => invoke("disconnect_remote_server"),
  refreshRemoteCapabilities: () => invoke("refresh_remote_server_capabilities"),
  prepareRemoteDeployment: (publicBaseUrl: string) => invoke<{ directory: string; publicBaseUrl: string; managementToken: string; vaultKey: string; composeCommand: string }>("prepare_remote_server_deployment", { input: { publicBaseUrl } }),
  remoteAction: (action: Record<string, unknown>, payload?: unknown) => invoke("execute_remote_server_action", { input: { action, payload: payload ?? null } }),
};

export function defaultWakeInput(name: string): Omit<WakeTask, "id" | "createdAtMs" | "updatedAtMs" | "trigger"> {
  return {
    name,
    enabled: true,
    accountSelector: { kind: "all_eligible" },
    windowKinds: ["primary", "secondary"],
    modelPolicy: { kind: "lightest_supported" },
    executionPolicy: "automatic",
    jitterSeconds: 0,
    maxAttemptsPerCycle: 1,
  };
}
