Get-Content: 
Line |
   2 |  Get-Content -Raw -LiteralPath 'work\github-config\ISSUE_TEMPLATE\bug_ …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'work\github-config\ISSUE_TEMPLATE\bug_report.yml' because it does not exist.
