Get-Content: 
Line |
   2 |  Get-Content -Raw -LiteralPath 'work\github-config\ISSUE_TEMPLATE\conf …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'work\github-config\ISSUE_TEMPLATE\config.yml' because it does not exist.
