Get-Content: 
Line |
   2 |  Get-Content -Raw -LiteralPath 'work\github-config\ISSUE_TEMPLATE\feat …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'work\github-config\ISSUE_TEMPLATE\feature_request.yml' because it does not exist.
