Get-Content: 
Line |
   2 |  Get-Content -Raw -LiteralPath 'work\github-config\ISSUE_TEMPLATE\ques …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'work\github-config\ISSUE_TEMPLATE\question.yml' because it does not exist.
