use reqwest::header::{HeaderMap, HeaderName, HeaderValue};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::fmt;

const MAX_CAPTURED_HEADER_VALUE_BYTES: usize = 32 * 1024;
const MAX_CAPTURED_HEADER_COUNT: usize = 64;
const MAX_CAPTURED_HEADER_BYTES: usize = 64 * 1024;

/// Header names that Basis Points may reuse from the current OAuth session.
/// Authentication, account binding, and protocol headers are generated by
/// Relay and are deliberately absent from this allowlist.
const ALLOWED_CAPTURED_HEADERS: &[(&str, &str)] = &[
    ("user-agent", "user-agent"),
    ("x-openai-account-user-id", "x-openai-account-user-id"),
    (
        "x-openai-internal-basispoints-browser-name",
        "x-openai-internal-basispoints-browser-name",
    ),
    (
        "x-openai-internal-basispoints-browser-ua-brands",
        "x-openai-internal-basispoints-browser-ua-brands",
    ),
    (
        "x-openai-internal-basispoints-browser-ua-mobile",
        "x-openai-internal-basispoints-browser-ua-mobile",
    ),
    (
        "x-openai-internal-basispoints-browser-ua-platform",
        "x-openai-internal-basispoints-browser-ua-platform",
    ),
    (
        "x-openai-internal-basispoints-client-agent-profile",
        "x-openai-internal-basispoints-client-agent-profile",
    ),
    (
        "x-openai-internal-basispoints-client-editor",
        "x-openai-internal-basispoints-client-editor",
    ),
    (
        "x-openai-internal-basispoints-client-host",
        "x-openai-internal-basispoints-client-host",
    ),
    (
        "x-openai-internal-basispoints-client-platform",
        "x-openai-internal-basispoints-client-platform",
    ),
    (
        "x-openai-internal-basispoints-client-platform-class",
        "x-openai-internal-basispoints-client-platform-class",
    ),
    (
        "x-openai-internal-basispoints-client-product",
        "x-openai-internal-basispoints-client-product",
    ),
    (
        "x-openai-internal-basispoints-client-runtime",
        "x-openai-internal-basispoints-client-runtime",
    ),
    (
        "x-openai-internal-basispoints-office-host",
        "x-openai-internal-basispoints-office-host",
    ),
    (
        "x-openai-internal-basispoints-office-platform",
        "x-openai-internal-basispoints-office-platform",
    ),
    ("x-stainless-arch", "x-stainless-arch"),
    ("x-stainless-lang", "x-stainless-lang"),
    ("x-stainless-os", "x-stainless-os"),
    ("x-stainless-package-version", "x-stainless-package-version"),
    ("x-stainless-retry-count", "x-stainless-retry-count"),
    ("x-stainless-runtime", "x-stainless-runtime"),
    ("x-stainless-runtime-version", "x-stainless-runtime-version"),
];

#[derive(Clone, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BasisPointsHeader {
    pub name: String,
    pub values: Vec<String>,
}

#[derive(Clone, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BasisPointsCapturedHeaders {
    entries: Vec<BasisPointsHeader>,
}

impl fmt::Debug for BasisPointsCapturedHeaders {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("BasisPointsCapturedHeaders")
            .field("count", &self.entries.len())
            .finish()
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BasisPointsHeadersError {
    InvalidName,
    InvalidValue,
    TooManyHeaders,
    TooLarge,
}

impl BasisPointsCapturedHeaders {
    pub fn from_json_values(
        headers: Option<&Value>,
        captured_headers: Option<&Value>,
    ) -> Result<Self, BasisPointsHeadersError> {
        let mut entries = Vec::new();
        collect_json_headers(headers, &mut entries)?;
        // The upstream contract gives captured_headers precedence over headers.
        collect_json_headers(captured_headers, &mut entries)?;
        Self::from_entries(entries)
    }

    pub fn from_entries(entries: Vec<BasisPointsHeader>) -> Result<Self, BasisPointsHeadersError> {
        let mut normalized = Vec::new();
        let mut total_bytes = 0usize;
        for entry in entries {
            let Some(name) = canonical_header_name(&entry.name) else {
                return Err(BasisPointsHeadersError::InvalidName);
            };
            let values = validate_values(&entry.values, &mut total_bytes)?;
            if values.is_empty() {
                continue;
            }
            if let Some(existing) = normalized
                .iter_mut()
                .find(|existing: &&mut BasisPointsHeader| existing.name == name)
            {
                existing.values = values;
            } else {
                if normalized.len() >= MAX_CAPTURED_HEADER_COUNT {
                    return Err(BasisPointsHeadersError::TooManyHeaders);
                }
                normalized.push(BasisPointsHeader {
                    name: name.to_string(),
                    values,
                });
            }
        }
        Ok(Self {
            entries: normalized,
        })
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    pub fn entries(&self) -> &[BasisPointsHeader] {
        &self.entries
    }

    pub fn apply(&self, headers: &mut HeaderMap) {
        for entry in &self.entries {
            let Ok(name) = HeaderName::from_bytes(entry.name.as_bytes()) else {
                continue;
            };
            headers.remove(&name);
            for value in &entry.values {
                if let Ok(value) = HeaderValue::from_str(value) {
                    headers.append(name.clone(), value);
                }
            }
        }
    }

    pub fn validate(&self) -> Result<(), BasisPointsHeadersError> {
        Self::from_entries(self.entries.clone()).map(|_| ())
    }
}

fn collect_json_headers(
    value: Option<&Value>,
    entries: &mut Vec<BasisPointsHeader>,
) -> Result<(), BasisPointsHeadersError> {
    let Some(object) = value.and_then(Value::as_object) else {
        return Ok(());
    };
    for (raw_name, raw_value) in object {
        let Some(name) = canonical_header_name(raw_name) else {
            continue;
        };
        let values = match raw_value {
            Value::String(value) => vec![value.clone()],
            Value::Array(values) => values
                .iter()
                .map(Value::as_str)
                .collect::<Option<Vec<_>>>()
                .map(|values| values.into_iter().map(str::to_string).collect())
                .unwrap_or_default(),
            _ => Vec::new(),
        };
        let values = validate_values(&values, &mut 0)?;
        if values.is_empty() {
            continue;
        }
        if let Some(existing) = entries.iter_mut().find(|existing| existing.name == name) {
            existing.values = values;
        } else {
            entries.push(BasisPointsHeader {
                name: name.to_string(),
                values,
            });
        }
    }
    Ok(())
}

fn validate_values(
    values: &[String],
    total_bytes: &mut usize,
) -> Result<Vec<String>, BasisPointsHeadersError> {
    let mut validated = Vec::with_capacity(values.len());
    for value in values {
        if value.len() > MAX_CAPTURED_HEADER_VALUE_BYTES
            || value.bytes().any(|byte| byte < 0x20 || byte == 0x7f)
        {
            return Err(BasisPointsHeadersError::InvalidValue);
        }
        let value = value.trim();
        if value.is_empty() {
            continue;
        }
        *total_bytes = total_bytes.saturating_add(value.len());
        if *total_bytes > MAX_CAPTURED_HEADER_BYTES {
            return Err(BasisPointsHeadersError::TooLarge);
        }
        validated.push(value.to_string());
    }
    Ok(validated)
}

fn canonical_header_name(name: &str) -> Option<&'static str> {
    ALLOWED_CAPTURED_HEADERS
        .iter()
        .find(|(allowed, _)| allowed.eq_ignore_ascii_case(name.trim()))
        .map(|(_, canonical)| *canonical)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn captured_headers_override_same_name_and_ignore_unsupported_names() {
        let headers = json!({
            "User-Agent": "old-agent",
            "Cookie": "secret=value",
            "x-stainless-os": "Windows"
        });
        let captured = json!({
            "user-agent": ["new-agent"],
            "x-stainless-os": "Darwin"
        });
        let parsed =
            BasisPointsCapturedHeaders::from_json_values(Some(&headers), Some(&captured)).unwrap();
        let mut output = HeaderMap::new();
        parsed.apply(&mut output);
        assert_eq!(output["user-agent"], "new-agent");
        assert_eq!(output["x-stainless-os"], "Darwin");
        assert!(!output.contains_key("cookie"));
    }

    #[test]
    fn invalid_captured_values_are_rejected() {
        let headers = json!({"user-agent": "invalid\nvalue"});
        assert_eq!(
            BasisPointsCapturedHeaders::from_json_values(Some(&headers), None),
            Err(BasisPointsHeadersError::InvalidValue)
        );
    }
}
