import { useState } from "react";
import { ClipboardCheck, Copy, Play, RefreshCw, Square, Wrench } from "lucide-react";
import { useTranslation } from "react-i18next";
import { relayCommands } from "../../api/commands";
import { Button, EmptyState, PageHeader, StatusBadge, Tabs, copyText } from "../../components/Ui";
import { useRelayState } from "../../state/RelayStateProvider";

type View = "endpoint" | "clients" | "diagnostics";

export function GatewayPage() {
  const { t } = useTranslation(); const { mode, runtime, readyState, busy, perform } = useRelayState(); const [view, setView] = useState<View>("endpoint"); const running = mode === "zenith" ? Boolean(readyState?.providerActive) : Boolean(runtime?.gateway.running); const endpoint = mode === "zenith" ? "https://api.zenithmarket.dev/v1" : runtime?.gateway.baseUrl ?? "";
  const action = mode === "zenith" ? null : <Button variant="primary" busy={busy === "gateway-toggle"} icon={running ? <Square aria-hidden /> : <Play aria-hidden />} onClick={() => perform("gateway-toggle", () => mode === "local" ? (running ? relayCommands.stopGateway() : relayCommands.startGateway()) : relayCommands.remoteAction({type:running?"stop_gateway":"start_gateway"}), running ? "feedback.stopped" : "feedback.started")}>{running ? t("gateway.stop") : t("gateway.start")}</Button>;
  return <section className="relay-page"><PageHeader title={t("nav.gateway")} subtitle={t(`gateway.subtitles.${mode}`)} actions={action} /><Tabs value={view} onChange={(id) => setView(id as View)} label={t("gateway.views")} items={[{id:"endpoint",label:t("gateway.endpoint")},{id:"clients",label:t("gateway.clientSetup")},{id:"diagnostics",label:t("gateway.diagnostics")}]}/>{view === "endpoint" ? <EndpointView running={running} endpoint={endpoint} /> : null}{view === "clients" ? <ClientSetup endpoint={endpoint} /> : null}{view === "diagnostics" ? <Diagnostics /> : null}</section>;
}

function EndpointView({ running, endpoint }: { running: boolean; endpoint: string }) {
  const { t } = useTranslation(); const { mode, runtime } = useRelayState();
  if (!endpoint) return <EmptyState title={t("gateway.emptyTitle")} description={t("gateway.emptyDescription")} />;
  return <div className="gateway-sections"><section><header><h2>{t("gateway.endpoint")}</h2><StatusBadge status={running ? "ready" : "warning"} label={running ? t("common.online") : t("common.offline")} /></header><div className="endpoint-line"><code>{endpoint}</code><Button variant="secondary" icon={<Copy aria-hidden />} onClick={() => copyText(endpoint)}>{t("common.copy")}</Button></div></section><section><h2>{t("gateway.runtime")}</h2><dl className="runtime-grid"><div><dt>{t("common.status")}</dt><dd>{running ? t("common.online") : t("common.offline")}</dd></div><div><dt>{t("common.models")}</dt><dd>{runtime?.gateway.visibleModelIds.length ?? "-"}</dd></div><div><dt>{t("pool.members")}</dt><dd>{runtime?.gateway.candidateCount ?? "-"}</dd></div><div><dt>{t("common.mode")}</dt><dd>{t(`modes.${mode}`)}</dd></div></dl></section><section><h2>{t("gateway.settings")}</h2><div className="settings-row"><label><span>{t("gateway.host")}</span><input value={mode === "local" ? "127.0.0.1" : new URL(endpoint).host} disabled /></label><label><span>{t("gateway.port")}</span><input value={mode === "local" ? "14998" : new URL(endpoint).port || "443"} disabled /></label><label><span>{t("gateway.bind")}</span><select disabled><option>{mode === "local" ? t("gateway.loopback") : t("gateway.serverManaged")}</option></select></label></div></section></div>;
}

function ClientSetup({ endpoint }: { endpoint: string }) {
  const { t } = useTranslation(); const { mode, runtime, perform, busy } = useRelayState(); const [client, setClient] = useState("codex"); const key = runtime?.keys[0];
  return <div className="client-setup"><div className="segmented">{["codex","opencode","other"].map((value) => <button type="button" key={value} className={client === value ? "active" : ""} onClick={() => setClient(value)}>{t(`clients.${value}`)}</button>)}</div><section className="config-preview"><header><h2>{t("gateway.generatedConfig")}</h2><Button variant="ghost" icon={<Copy aria-hidden />} onClick={() => copyText(`base_url = "${endpoint}"`)}>{t("common.copy")}</Button></header><pre>{`base_url = "${endpoint}"\nwire_api = "responses"\nrequires_openai_auth = true`}</pre></section><div className="inline-actions"><Button variant="primary" busy={busy === "profile-attach"} disabled={mode !== "local" || !key} icon={<ClipboardCheck aria-hidden />} onClick={() => key && perform("profile-attach", () => relayCommands.attachCodexGateway(key.id), "feedback.profileAttached")}>{t("profiles.attachCurrent")}</Button><Button variant="secondary" busy={busy === "profile-restore"} disabled={mode !== "local"} onClick={() => perform("profile-restore", relayCommands.restoreCodex, "feedback.restored")}>{t("profiles.restore")}</Button></div><p className="form-note">{mode !== "local" ? t("gateway.manualOnly") : t("profiles.backupHint")}</p></div>;
}

function Diagnostics() {
  const { t } = useTranslation(); const { mode, runtime, perform, busy } = useRelayState(); const source = runtime?.sources[0];
  return <div className="diagnostics-list"><section><Wrench aria-hidden /><div><strong>{t("gateway.endpointHealth")}</strong><span>{runtime?.gateway.running ? t("common.ready") : t("common.offline")}</span></div><Button variant="secondary" busy={busy === "diagnostics"} onClick={() => perform("diagnostics", async () => { if (mode === "local" && source) await relayCommands.testSource(source.id); else if (mode === "remote") await relayCommands.refreshRemoteCapabilities(); }, "feedback.checked")}>{t("common.run")}</Button></section><section><RefreshCw aria-hidden /><div><strong>{t("gateway.streamTest")}</strong><span>{t("gateway.streamHint")}</span></div><StatusBadge status={runtime?.gateway.running ? "ready" : "disabled"} label={runtime?.gateway.running ? t("common.available") : t("common.disabled")} /></section><section><ClipboardCheck aria-hidden /><div><strong>{t("gateway.supportBundle")}</strong><span>{t("gateway.redactedLogs")}</span></div><Button variant="secondary" disabled>{t("common.export")}</Button></section></div>;
}
